[package]
name = "redis-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.7.1"
clap = { version = "4.5.13", features = ["derive"] }
regex = "1.10.6"
tokio = { version = "1.39.2", features = ["macros", "net", "rt-multi-thread"] }
